project:
  type: website

website:
  title: "Running LLMs on HPC"
  sidebar:
    contents:
      - href: vsc_about.qmd
        text: Home
      - href: vsc_basics.qmd
        text: HPC & LLM Basics
      - href: vsc_setup.qmd
        text: Environment Setup
      - href: vsc_shoot.qmd
        text: Running Jobs
      - href: vsc_jobs.qmd
        text: Best Practices
  

format:
  html:
    theme: [cosmo, custom.scss]
    toc: true
